import { UserAddress } from "@tower-defense/utils";
export declare function indexerQueryAccountNfts(account: string, size?: number, page?: number): string;
export declare function indexerQueryHistoricalOwner(contract: string, tokenId: number, blockHeight: number): string;
export declare function indexerQueryTitleImage(contract: string, tokenId: number): string;
export declare function backendQueryLobbyState(lobbyID: string): string;
export declare function backendQueryLatestProcessedBlockHeight(): string;
export declare function backendQueryUserLobbiesBlockheight(wallet: UserAddress, blockHeight: number): string;
export declare function backendQueryRoundStatus(lobbyID: string, roundNumber: number): string;
export declare function backendQueryUserStats(wallet: UserAddress): string;
export declare function backendQueryUserNft(wallet: UserAddress): string;
export declare function backendQueryUserLobbies(wallet: UserAddress, count?: number, page?: number): string;
export declare function backendQueryOpenLobbies(count?: number, page?: number): string;
export declare function backendQueryRoundExecutor(lobbyID: string, roundNumber: number): string;
export declare function backendQueryMatchExecutor(lobbyID: string): string;
